# Generated by Django 4.0.4 on 2022-05-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='short_description',
            field=models.CharField(default='---', max_length=200),
            preserve_default=False,
        ),
    ]
