# Generated by Django 4.0.4 on 2022-05-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_generallink_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='generallink',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
