# Generated by Django 4.0.4 on 2022-05-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='generallink',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
